// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: user.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileReq) Reset() {
	*x = GetProfileReq{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileReq) ProtoMessage() {}

func (x *GetProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileReq.ProtoReflect.Descriptor instead.
func (*GetProfileReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type GetProfileRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRes) Reset() {
	*x = GetProfileRes{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRes) ProtoMessage() {}

func (x *GetProfileRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRes.ProtoReflect.Descriptor instead.
func (*GetProfileRes) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetProfileRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserReq) Reset() {
	*x = RegisterUserReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserReq) ProtoMessage() {}

func (x *RegisterUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserReq.ProtoReflect.Descriptor instead.
func (*RegisterUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRes) Reset() {
	*x = RegisterUserRes{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRes) ProtoMessage() {}

func (x *RegisterUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRes.ProtoReflect.Descriptor instead.
func (*RegisterUserRes) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterUserRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterUserRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserReq) Reset() {
	*x = LoginUserReq{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserReq) ProtoMessage() {}

func (x *LoginUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserReq.ProtoReflect.Descriptor instead.
func (*LoginUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRes) Reset() {
	*x = LoginUserRes{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRes) ProtoMessage() {}

func (x *LoginUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRes.ProtoReflect.Descriptor instead.
func (*LoginUserRes) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *LoginUserRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UpdateUserNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Newusername   string                 `protobuf:"bytes,1,opt,name=newusername,proto3" json:"newusername,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserNameReq) Reset() {
	*x = UpdateUserNameReq{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserNameReq) ProtoMessage() {}

func (x *UpdateUserNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserNameReq.ProtoReflect.Descriptor instead.
func (*UpdateUserNameReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserNameReq) GetNewusername() string {
	if x != nil {
		return x.Newusername
	}
	return ""
}

type UpdatePasswordReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Currentpassword string                 `protobuf:"bytes,1,opt,name=currentpassword,proto3" json:"currentpassword,omitempty"`
	Newpassword     string                 `protobuf:"bytes,2,opt,name=newpassword,proto3" json:"newpassword,omitempty"`
	Confirmpassword string                 `protobuf:"bytes,3,opt,name=confirmpassword,proto3" json:"confirmpassword,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePasswordReq) Reset() {
	*x = UpdatePasswordReq{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordReq) ProtoMessage() {}

func (x *UpdatePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordReq.ProtoReflect.Descriptor instead.
func (*UpdatePasswordReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePasswordReq) GetCurrentpassword() string {
	if x != nil {
		return x.Currentpassword
	}
	return ""
}

func (x *UpdatePasswordReq) GetNewpassword() string {
	if x != nil {
		return x.Newpassword
	}
	return ""
}

func (x *UpdatePasswordReq) GetConfirmpassword() string {
	if x != nil {
		return x.Confirmpassword
	}
	return ""
}

type UpdateEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Newemail      string                 `protobuf:"bytes,1,opt,name=newemail,proto3" json:"newemail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailReq) Reset() {
	*x = UpdateEmailReq{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailReq) ProtoMessage() {}

func (x *UpdateEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailReq.ProtoReflect.Descriptor instead.
func (*UpdateEmailReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateEmailReq) GetNewemail() string {
	if x != nil {
		return x.Newemail
	}
	return ""
}

type UpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRes) Reset() {
	*x = UpdateRes{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRes) ProtoMessage() {}

func (x *UpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRes.ProtoReflect.Descriptor instead.
func (*UpdateRes) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\"\x0f\n" +
	"\rGetProfileReq\"A\n" +
	"\rGetProfileRes\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"_\n" +
	"\x0fRegisterUserReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"A\n" +
	"\x0fRegisterUserRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"F\n" +
	"\fLoginUserReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"$\n" +
	"\fLoginUserRes\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"5\n" +
	"\x11UpdateUserNameReq\x12 \n" +
	"\vnewusername\x18\x01 \x01(\tR\vnewusername\"\x89\x01\n" +
	"\x11UpdatePasswordReq\x12(\n" +
	"\x0fcurrentpassword\x18\x01 \x01(\tR\x0fcurrentpassword\x12 \n" +
	"\vnewpassword\x18\x02 \x01(\tR\vnewpassword\x12(\n" +
	"\x0fconfirmpassword\x18\x03 \x01(\tR\x0fconfirmpassword\",\n" +
	"\x0eUpdateEmailReq\x12\x1a\n" +
	"\bnewemail\x18\x01 \x01(\tR\bnewemail\"%\n" +
	"\tUpdateRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa2\x02\n" +
	"\vUserService\x12.\n" +
	"\bRegister\x12\x10.RegisterUserReq\x1a\x10.RegisterUserRes\x12%\n" +
	"\x05Login\x12\r.LoginUserReq\x1a\r.LoginUserRes\x120\n" +
	"\x0eUpdateUserName\x12\x12.UpdateUserNameReq\x1a\n" +
	".UpdateRes\x120\n" +
	"\x0eUpdatePassword\x12\x12.UpdatePasswordReq\x1a\n" +
	".UpdateRes\x12*\n" +
	"\vUpdateEmail\x12\x0f.UpdateEmailReq\x1a\n" +
	".UpdateRes\x12,\n" +
	"\n" +
	"GetProfile\x12\x0e.GetProfileReq\x1a\x0e.GetProfileResB\x03Z\x01.b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_proto_goTypes = []any{
	(*GetProfileReq)(nil),     // 0: GetProfileReq
	(*GetProfileRes)(nil),     // 1: GetProfileRes
	(*RegisterUserReq)(nil),   // 2: RegisterUserReq
	(*RegisterUserRes)(nil),   // 3: RegisterUserRes
	(*LoginUserReq)(nil),      // 4: LoginUserReq
	(*LoginUserRes)(nil),      // 5: LoginUserRes
	(*UpdateUserNameReq)(nil), // 6: UpdateUserNameReq
	(*UpdatePasswordReq)(nil), // 7: UpdatePasswordReq
	(*UpdateEmailReq)(nil),    // 8: UpdateEmailReq
	(*UpdateRes)(nil),         // 9: UpdateRes
}
var file_user_proto_depIdxs = []int32{
	2, // 0: UserService.Register:input_type -> RegisterUserReq
	4, // 1: UserService.Login:input_type -> LoginUserReq
	6, // 2: UserService.UpdateUserName:input_type -> UpdateUserNameReq
	7, // 3: UserService.UpdatePassword:input_type -> UpdatePasswordReq
	8, // 4: UserService.UpdateEmail:input_type -> UpdateEmailReq
	0, // 5: UserService.GetProfile:input_type -> GetProfileReq
	3, // 6: UserService.Register:output_type -> RegisterUserRes
	5, // 7: UserService.Login:output_type -> LoginUserRes
	9, // 8: UserService.UpdateUserName:output_type -> UpdateRes
	9, // 9: UserService.UpdatePassword:output_type -> UpdateRes
	9, // 10: UserService.UpdateEmail:output_type -> UpdateRes
	1, // 11: UserService.GetProfile:output_type -> GetProfileRes
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
